<!-- Start Page Banner Area -->
<div class="page-banner-area">
   <div class="container">
      <div class="row">
         <div class="col-md-12">
            <div class="page-title">
               <h2>Kontakt</h2>
               <span class="sub-title">Über uns</span>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- End Pages Banner Area -->

<!-- Start Login Form -->
<div class="container-area container-padding">
   <div class="container">
      <div class="row">
         <div class="col-md-6">
            <div class="login-form">
              <div class="row">
	            	<h4>Öffnungszeiten</h4>
								Mo - Fr <br /> 
								08:00 - 17:00<br /><br />  

								<h4>Adresse</h4>
								Web Weaves<br /> 
								Weaver Customer Care System<br />
								Obermühleweid 4<br /> 
								6330 Cham<br /><br />

								<h4>E-Mail</h4>
								info@webweaves.ch<br /><br />

								<h4>Telefonnummer</h4>
								+41 79 754 98 29<br /> 
              </div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- End Login Form -->