<!-- Start Page Banner Area -->
<div class="page-banner-area">
   <div class="container">
      <div class="row">
         <div class="col-md-12">
            <div class="page-title">
               <h2>Impressum</h2>
               <span class="sub-title">Über uns</span>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- End Pages Banner Area -->

<div class="container-area container-padding">
   <div class="container">
      <div class="row">
         <div class="col-md-8">
            <div class="login-form">
              <div class="row">
                  <h2>Urheberrecht</h2>
                  <p>Die auf dieser Webseite veröffentlichten Inhalte, Werke und bereitgestellten Informationen unterliegen dem Schweizerischen Urheberrecht und Leistungsschutzrecht. Jede Art der Vervielfältigung, Bearbeitung, Verbreitung, Einspeicherung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechts bedarf der vorherigen schriftlichen Zustimmung des jeweiligen Rechteinhabers. Das unerlaubte Kopieren/Speichern der bereitgestellten Informationen auf diesen Webseiten ist nicht gestattet und strafbar.<br /><br />

                  	Unsere Kontaktdaten finden Sie unter <a href="/about/contact">KONTAKT</a>.</p>
              </div>
            </div>
         </div>
      </div>
   </div>
</div>

