<!-- Start Page Banner Area -->
<div class="page-banner-area">
   <div class="container">
      <div class="row">
         <div class="col-md-12">
            <div class="page-title">
               <h2>Über uns</h2>
               <span class="sub-title"></span>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- End Pages Banner Area -->

<!-- Start Login Form -->
<div class="container-area container-padding">
   <div class="container">
      <div class="row">
         <div class="col-md-6">
            <div class="login-form">
              <div class="row">
                <h2>Weaver - Customer Care System</h2>
                <p>Wir möchten, dass der Kunde mehrere Möglichkeiten hat, mit uns in Kontakt zu treten. Egal ob über Telefon, E-Mail oder unserem Customer Care System erreichbar sein.<br /><br /> Mit Hilfe von "Weaver" können unsere Kunden ein Anliegen oder eine Störung erfassen. Unsere Mitarbeiter werden das Anliegen bearbeiten und der Kunde wird über das System bei Statusänderungen benachrichtigt.</p><br />
              </div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- End Login Form -->