<!-- Start Page Banner Area -->
<div class="page-banner-area">
   <div class="container">
      <div class="row">
         <div class="col-md-12">
            <div class="page-title">
               <h2>Benutzerhandbuch</h2>
               <span class="sub-title">Über uns</span>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- End Pages Banner Area -->

<!-- Start Login Form -->
<div class="container-area container-padding">
   <div class="container">
      <div class="row">
         <div class="col-md-8">
            <div class="login-form">
              <div class="row">
                  <h2>Downloads</h2>
                  <p>Hier finden Sie unsere Benutzerhandbücher für Account/Login sowie für die Support-Tickets. Diese können Sie als PDF downloaden und alle nötigen Informationen daraus entnehmen.</p>
                  <br />

	            	<h4>Account</h4>
						<a target="_blank" href="/public/downloads/benutzerhandbuch-account.pdf"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> PDF Download</a>
                  <br /><br />
                  <h4>Tickets (Support)</h4>
                  <a target="_blank" href="/public/downloads/benutzerhandbuch-tickets-support.pdf"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> PDF Download</a>
              </div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- End Login Form -->