<!-- Start Page Banner Area -->
<div class="page-banner-area">
   <div class="container">
      <div class="row">
         <div class="col-md-12">
            <div class="page-title">
               <h2>Passwort vergessen</h2>
               <span class="sub-title">Account</span>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- End Pages Banner Area -->

<!-- Start Login Form -->
<div class="container-area container-padding">
   <div class="container">
      <div class="row">
         <div class="col-md-6">
            <div class="form manage">
               <form name="forgotpasswordform" id="forgotpasswordform" action="<?=$this->url('account', ['action' => 'forgotpassword'])?>" method="post">
                  <div class="row">
                      <h2>Reset-Link anfordern</h2>
                      <p>Bitte geben Sie Ihre E-Mail Adresse ein, damit wir Ihnen einen Reset-Link zusenden können.</p><br />                      
                      <div class="col-md-12 p-0">
                          <label for="email">E-Mail </label>
                          <input type="text" name="email" id="email" value="<?=$formData['email']?>" tabindex="1" required>
                      </div>                      

                      <input type="submit" value="Senden" name="btnSend" class="btn hover-bg">

                      <div class="row">
                        <div class="col-md-12 error-messages">
                          <?php foreach ($alerts as $alert) : ?>
                            <?=$alert?><br>
                          <?php endforeach; ?>
                        </div>
                        <div class="col-md-12 success-messages">
                          <? if ($success == true) { ?>
                              Sie erhalten in Kürze eine E-Mail mit einem Reset-Link.
                          <? } ?>
                        </div>
                      </div>
                  </div>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- End Login Form -->