<!-- Start Page Banner Area -->
<div class="page-banner-area">
   <div class="container">
      <div class="row">
         <div class="col-md-12">
            <div class="page-title">
               <h2>Logout</h2>
               <span class="sub-title">Account</span>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- End Pages Banner Area -->

<!-- Start Login Form -->
<div class="container-area container-padding">
   <div class="container">
      <div class="row">
         <div class="col-md-6">
            <div class="login-form">
               <h2 class="title">Logout erfolgreich</h2>
                <p>
                  Sie sind nun ausgeloggt.<br>
                  Klicken Sie <a href="/">hier</a>, um auf die Startseite zu gelangen.
                </p>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- End Login Form -->