<!-- Start Page Banner Area -->
<div class="page-banner-area">
   <div class="container">
      <div class="row">
         <div class="col-md-12">
            <div class="page-title">
               <h2>Passwort vergessen</h2>
               <span class="sub-title">Account</span>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- End Pages Banner Area -->

<!-- Start Login Form -->
<div class="container-area container-padding">
   <div class="container">
      <div class="row">
         <div class="col-md-6">
            <div class="form manage">
               <form name="forgotpasswordform" id="forgotpasswordform" action="<?=$this->url('account', ['action' => 'resetpassword', 'id' => $resetId])?>" method="post">
                  <div class="row">
                      <h2>Passwort zurücksetzen</h2>
                      <p>Bitte geben Sie Ihre E-Mail Adresse und das neue Passwort ein.</p><br />                      
                      <div class="col-md-12 p-0">
                          <label for="email">E-Mail </label>
                          <input type="text" name="email" id="email" value="<?=$formData['email']?>" tabindex="1" required>
                      </div>
                      <div class="col-md-12 p-0">
                          <div class="col-md-6 p-0">
                            <label for="newpassword">Neues Passwort</label>
                            <input type="password" name="newpassword" id="newpassword" value="<?=$formData['newpassword']?>" tabindex="2" required>
                          </div>
                          <div class="col-md-6" style="padding-right: 0">
                            <label for="newpasswordrepeat">Neues Passwort erneut</label>
                            <input type="password" size="20" name="newpasswordrepeat" id="newpasswordrepeat" value="<?=$formData['newpasswordrepeat']?>" tabindex="3" required>
                          </div>
                      </div>

                      <input type="submit" value="Zurücksetzen" name="btnReset" class="btn hover-bg">

                      <div class="row">
                        <div class="col-md-12 error-messages">
                          <?php foreach ($alerts as $alert) : ?>
                            <?=$alert?><br>
                          <?php endforeach; ?>
                        </div>
                        <div class="col-md-12 success-messages">
                          <? if ($success == true) { ?>
                              Ihr Passwort wurde erfolgreich zurückgesetzt.
                          <? } ?>
                        </div>
                      </div>
                  </div>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- End Login Form -->