<!-- Start Page Banner Area -->
<div class="page-banner-area">
   <div class="container">
      <div class="row">
         <div class="col-md-12">
            <div class="page-title">
               <h2>Ticket Verwaltung</h2>
               <span class="sub-title"></span>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- End Pages Banner Area -->

<div class="container container-padding">
   <div class="container">
      <div class="row">
         <div class="col-md-12">
          <h3>
            Hallo <?=$user->firstname." ".$user->lastname?>
          </h3>
         </div>
         <div class="col-sm-6 col-md-4">
            <div class="update-box">
               <div class="update-version">
                  <h2>Tickets</h2>
                  <span class="badge update-badge">1</span>
               </div>
               <p>Hier finden Sie alle Tickets zu Ihren Anliegen oder Störungen.</p>

               <a href="<?=$this->url('ticket', ['action' => 'overview'])?>" class="btn hover-bg">Übersicht</a><br /><br />
            </div>
         </div>
         <div class="col-sm-6 col-md-4">
            <div class="update-box">
               <div class="update-version">
                  <h2>Ticket erstellen</h2>
               </div>
               <p>Hier können Sie ein neues Ticket erstellen.</p>

               <a href="<?=$this->url('ticket', ['action' => 'create'])?>" class="btn hover-bg">Ticket erstellen</a>
            </div>
         </div>

         <? if ($user->type == 2) { ?>
          
         <? } ?>
      </div>
   </div>
</div>