<div class="slider-area">
    <div class="container-fluid">
        <div class="row">
            <div class="slider-wrapper-bluegray">
               <div class="slider-fixed-text">
                    <h1>Weaver</h1>
                    <h2>Customer Care System</h2>
                    <p>Die Web Weaves Spezialisten beraten und assistieren Privatpersonen und KMU tagtäglich, die Daten sind alle in der Schweiz gespeichert – für einen wirkungsvollen und sicheren Internetauftritt.</p><br />
                    <p>Sie können unsere Supportmitarbeitenden über unser Customer Care System "Weaver" kontaktieren, wenn Sie eine Frage oder ein Problem haben. Unsere Kunden besitzen einen persönlichen Account, bitte melden Sie sich an oder registrieren Sie sich.</p>
                    <div class="slider-buttons">
                        <a href="<?=$this->url('account', ['action' => 'login'])?>" class="btn white-bg">Login</a>
                        <a href="<?=$this->url('account', ['action' => 'manage'])?>" class="btn white-bg">Re­gis­t­rie­rung</a>
                    </div>
               </div>
            </div>
        </div>
    </div>
</div>